command = "service"
isd_as = "1-150"
mode = "as"

[metrics]
prometheus = "127.0.0.1:33401"

[bootstrap]
server = "127.0.0.1:8041"
# allowedSubnets = [""] # TODO: Rethink this

[pila]
server = "127.0.0.1:8843"
ca_key_path = "./config/crypto/as/cp-as.key"
ca_cert_path = "./config/crypto/as/ISD1-AS150.pem"