version: "3.4"
services:
  rnode_150_br0:
    image: ubuntu:22.10
    container_name: as150full
    command: [ "bash", "/root/AS150/run.sh" ]
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
    privileged: true
    volumes:
      - "./AS150:/root/AS150"
      - "./scion-as:/root/AS150/scion-as"
    networks:
      net_150_net0:
        ipv4_address: 10.150.0.254
      net_ix_ix100:
        ipv4_address: 10.100.0.150

  rnode_151_br0:
    image: ubuntu:22.10
    container_name: as151full
    command: [ "bash", "/root/AS151/run.sh" ]
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
    privileged: true
    volumes:
      - "./AS151:/root/AS151"
      - "./scion-as:/root/AS151/scion-as"
    networks:
      net_151_net0:
        ipv4_address: 10.151.0.254
      net_ix_ix100:
        ipv4_address: 10.100.0.151

networks:
  net_150_net0:
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.150.0.0/24

  net_151_net0:
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.151.0.0/24

  net_ix_ix100:
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.100.0.0/24
